### ISSUE TITLE
annotation file is blank

### ISSUE THREAD

**Issue by A00TB** [btcrabb/SlideSeg#10]
Hi,

I have an annotation file corresponding to a ndpi whole slide image. However this module does not recognise any of the annotations despite processing the slides.

I have attached the annotated xml file (originally an ndpi file). 

Is there a reason why this happens?

[141969 -2 - grade12018-05-22 03.06.15.ndpi.txt](https://github.com/btcrabb/SlideSeg/files/2251313/141969.-2.-.grade12018-05-22.03.06.15.ndpi.txt)

**Comment by btcrabb** [comment]
Hi Taran,

SlideSeg uses the package xml.etree.ElementTree to parse the xml files; more specifically, it looks for 'Regions' corresponding to annotations in the xml file. The lines of code that perform this operation can be found in the main slideseg.py file, lines 215 through 222:

215    for filename in os.listdir(path):
216         # Import xml file and get root
217         tree = ET.parse('{0}/{1}'.format(path, filename))
218         root = tree.getroot()
219
220        # Find data in xml file
221        for reg in root.iter('Region'):
222             key = reg.get('Text').upper()

I'm guessing that your conversion from the ndpi file to the xml file is causing your errors. Looking at your file, it show's no 'Regions' corresponding to annotations. Take a look at the example xml file to view the formatting that slideseg expects. 

You will likely have to write your own code to parse the xml file.  One thing to try would be changing the 'Region' in line 221 to 'annotation' since that is what appears in your xml file. 

Best of luck!

**Comment by A00TB** [comment]
Great, many thanks for the reply.

Would you be able to tell me what software you used to create the annotations you supply in the example.xml file?

Kind regards,

Taran

**Comment by btcrabb** [comment]
Hi Taran,

Sorry to disappoint, but I didn't create the XML file myself. It was obtained from a local pathologist and I am not sure which software was used.
