### ISSUE TITLE
Dimension Issue

### ISSUE THREAD

**Issue by hitesha14** [btcrabb/SlideSeg#13]
While running the code on my dataset. I encountered the following error all input arrays must have same dimensions.

The stack trace of the error is given below:
  File "main.py", line 32, in <module>
    main()
  File "main.py", line 28, in main
    slideseg.run(params, filename)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\SlideSeg-master\SlideSeg-master\sl
ideseg.py", line 522, in run
    _mask, _annotations, filename, _suffix, _save_all, _save_ratio)
  File "C:\Users\hits\Anaconda3\envs\SlideSeg\SlideSeg-master\SlideSeg-master\sl
ideseg.py", line 450, in getchips
    pix_list = np.unique(img_mask)
  File "C:\Users\hits\Anaconda3\envs\py34\lib\site-packages\numpy\lib\arraysetop
s.py", line 200, in unique
    flag = np.concatenate(([True], aux[1:] != aux[:-1]))
ValueError: all the input arrays must have same number of dimensions

Please have a look at the error and let me know how can it be resolved @btcrabb

**Comment by btcrabb** [comment]
It looks like you are running NumPy on Python 3.4.  Slideseg was programmed to run on Python 2.7 and hasn't been updated since. Since it also looks like you installed the SlideSeg conda environment, which would have the appropriate versions, you probably have the newer version of NumPy and python in your PATH variable since it calls it in this line:

File "C:\Users\hits\Anaconda3\envs\py34\lib\site-packages\numpy\lib\arraysetop. 

Make sure the program is utilizing the correct NumPy version and I bet your problem will be resolved.

**Comment by hitesha14** [comment]
I resolved this issue. Hence closing it..
