### ISSUE TITLE
Issues processing .scn (Leica) Images with SlideSeg

### ISSUE THREAD

**Issue by hitesha14** [btcrabb/SlideSeg#14]
### The image patches or chips are in dark black in colour with no image clarity.

I have been trying to extract patches from a small number of .scn images (Whole Slide Images). However the image patches or chips received turn out to be blank and black in colour.  The images have annotations present in the xml file.

I have tried to modify the parameters.txt file to improve the output of the chips but it seems to have no avail. The output cannot be used used for any further Machine Learning Processing, few image chips have some part of the original .scn image but it doesn't seem like a chip but a rather a sort of segment however most of the chips are dark black and blank.

I have tried on different systems with different configurations but all of them give similar result. I have followed all the steps mentioned in the SlideSeg readme file and all the instructions given by you. I am attaching few image chips here. Please have a look at them and hope the issue gets resolved. @btcrabb 

![2367-18-11_2018-11-03 16_30_21 scn_0_0_40960](https://user-images.githubusercontent.com/8632760/49874139-b6ec3f00-fe43-11e8-83a8-fc8c14ba84d5.jpg)
![2367-18-11_2018-11-03 16_30_21 scn_1_0_4096](https://user-images.githubusercontent.com/8632760/49874140-b6ec3f00-fe43-11e8-8f24-5aba8fdae3de.jpg)
![2367-18-11_2018-11-03 16_30_21 scn_3_0_0](https://user-images.githubusercontent.com/8632760/49874141-b6ec3f00-fe43-11e8-83f1-96531773a3de.jpg)
![2367-18-11_2018-11-03 16_30_21 scn_4_0_0](https://user-images.githubusercontent.com/8632760/49874142-b784d580-fe43-11e8-9cb2-846f6df2055e.jpg)

**Comment by btcrabb** [comment]
Interesting, it’s not immediately clear what is causing this problem. Would you mind posting the parameters you used? Another thing to check would be whether or not the problem is with opening and rendering the images or with the processing performed by SlideSeg. Have you attempted to open this file using just the openslide software? This would tell you whether or not the images are even being opened correctly in the first place, which might be a good place to start. The image chips you posted make me think that the issue is related to a scaling issue between the different levels and dimensions of the WSI. Are all of these chips you posted from the same level? Let me know what you find out.

**Comment by hitesha14** [comment]
Hello @btcrabb:

Pertaining to the above issue mentioned I have tried all possiblities. I have opened the file with DeepZoom . Also my image file is generated from Leica. I have opened the file in aperio imagescope as well.  It opens fine and works fine, I am attaching the xml and the parameters file used for your reference Please do let me know. Since I still encounter black patches. I am unable to make much progress. It would be very useful if you could suggest me a solution to the above mentioned problem.

Regards,
Hitesha

[files.zip](https://github.com/btcrabb/SlideSeg/files/2906653/files.zip)

**Comment by hitesha14** [comment]
Hello @btcrabb 

I request you to look into the issue, I am unable to proceed further. There seems to be issue with level. But I am unsure of how to proceed with it. I had already attached the zip file. If you could please check out the issue asap.

Regards,
Hitesha

**Comment by btcrabb** [comment]
Hello @hitesha14 ,

I was able to look at your issues again briefly and had a few questions. The images you attached above are 4096x4096, but your parameters define the image output as 128x128. Are these not the output from the code? How are you generating these images?

Also, I agree with you, it is probably an issue with the level. I would make sure that the mask you are generating is the same size as your original .scn image and that it is scaling appropriately for all of the lower levels.  You could do this by just adding some print statements and making sure your annotation mask is being generated appropriately. 

I have not been able to reproduce your issue; however, I am happy to assist when and where I can. I would recheck that you are using the correct versions for all of the libraries and try running the code with save_all = False so that you only save image chips that are supposed to be annotated.  Let me know if you are able to find the problem and what can be done to avoid it in the future. 

Best of luck!
