### ISSUE TITLE
NDPI/NDPA annotations and key generation 

### ISSUE THREAD

**Issue by qalid7** [btcrabb/SlideSeg#15]
Hi

First of all, what a wonderful tool! I hope it works! 

I've free-hand annotations on an ndpi file (the output by default is xml/ndpa). I'm struggling in the "translation" part to generate the key.

Runs fine at first:
`C:\Tools\anaconda3\envs\SlideSeg\python.exe X:/functional/SlideSeg/main.py
running __main__ with parameters: {'save_ratio': 'inf', 'format': 'jpg', 'tags': '1', 'slide_path': 'images/', 'overlap': '1', 'save_all': 'True', 'xml_path': 'xml/', 'output_dir': 'output/', 'key': '', 'print': '1', 'quality': '100', 'size': '128'}`
`loading Patient1.ndpi
Patient1.ndpi loaded successfully
loading annotation data from xml//Patient1.ndpi.xml
Could not find , generating new file...`

But then I see this:

Traceback (most recent call last):
  File "X:/functional/SlideSeg/main.py", line 30, in <module>
    main()
  
File "X:/functional/SlideSeg/main.py", line 27, in main
    slideseg.run(params, filename)
  
File "X:\functional\SlideSeg\slideseg.py", line 510, in run
    _mask, _annotations = makemask(_key, _size, '{0}{1}'.format(_xml_path, xml_file))
 
 File "X:\functional\SlideSeg\slideseg.py", line 81, in makemask
    generatekey('{0}'.format(annotation_key), os.path.split(xml_path)[0])
  
File "X:\functional\SlideSeg\slideseg.py", line 233, in generatekey
    writeannotations(annotation_key, annotations)
 
 File "X:\functional\SlideSeg\slideseg.py", line 196, in writeannotations
    file = open(annotation_key, "w+")
IOError: [Errno 22] invalid mode ('w+') or filename: ''

I must mention that the ndpi annotation file looks quite different to the provided example. How can we fix this? Just an example: 

![image](https://user-images.githubusercontent.com/35524818/51699285-44ef4400-2004-11e9-8e6b-629f9d2fb8ff.png)

![image](https://user-images.githubusercontent.com/35524818/51699317-59334100-2004-11e9-95ed-d3098df47767.png)

They're all just freehand regions, I see "titles" not really "attributes" or IDs...

**Comment by btcrabb** [comment]
Hi qalid7!

I’m willing to bet that the filename of your .xml file (Patient1.ndpi.xml) is causing the issue since the os.path.split() function will be confused be the two periods. Try removing the first period and let me know if that works. 

In regards to the differences in the annotation file, check out lines 86, 87, 96, and 97 in slideseg.py. You may just have to change these to things like “title” and “pointlist” to better fit your file. That way, the xml parser will be looking for the correct headings. Let me know if any of those suggestions helps. You will also have to make the same changes to lines 221 and 222, when the annotation key is created for the first time.

**Comment by qalid7** [comment]
`IOError: [Errno 2] No such file or directory: 'xml/Patient1.ndpi.xml'` <- this settles the first suggestion if I remove `.ndpi`. I think the code takes care of the "filename.extension".xml. 

Working on the other suggestions now thanks!

**Comment by qalid7** [comment]
@btcrabb I think I may need your help please. Here are the four elements to be modified in the lines you mentioned:

-Region
-Text
-Vertices
-Vertex 

I'm not sure about the first two looking at the example. It seems like some sort of multi regional annotations linked to each other somehow. My file has very basic annotations, freehand drawings on large sections and that's about it. 

Can you help extracting the replacements please? Here's an entire region from within 1 xml file (I've multiple of those as seen in the image above):

![image](https://user-images.githubusercontent.com/35524818/51742610-2c2d6f80-2092-11e9-8979-d957d1c07ffb.png)

**Comment by qalid7** [comment]
Just to add something, I believe the format of your example xml is quite different to this one, e.g. `<x>-4850859</x>
                    <y>-2624309</y>` 

in your file this is `X=""` and so on..

**Comment by btcrabb** [comment]
Glad the first suggestion was helpful! 

In regards to the second, I believe you are going to have to change a fair amount of things (potentially even rewrite a few sections) to get this to work with the ndpa files. That being said, it's definitely possible. 

The first thing I would do is run the following lines in a command prompt:

![image](https://user-images.githubusercontent.com/31868269/51749759-7b14de00-206d-11e9-9a9b-d325c40ce7ae.png)

This will tell you the root structure of your file and give you a better idea what needs to be changed. From just looking at your file, I believe you'll be able to switch this section: 

![image](https://user-images.githubusercontent.com/31868269/51749825-a8fa2280-206d-11e9-997d-2e9b5a92a2f1.png)

To something like, 

![image](https://user-images.githubusercontent.com/31868269/51750105-4e14fb00-206e-11e9-851e-5779c703c5c0.png)

However, this method will assign each annotation a different key and color (just based on the Id's in your file) which might not be ideal for your application. You'll have to play around with it to see what works best for you. An alternative would be using the 'type=' or 'displayname=' from further down in the root structure. 

You should be able to replace 'Vertices' and 'Vertex' with 'pointlist' and 'point' respectively; however, you won't be able to use the .get() command because of the differences you pointed out in the X and Y. You'll likely have to use another .iter() command here. One more thing, it looks like your points are negative? I'm not sure how the pixels are stored in your file, but SlideSeg was made with the assumption that the top left pixel is (0,0). You may have to do a mathematical transformation to adjust the pixel locations in your file.

**Comment by qalid7** [comment]
just to confirm, does this mean the file is loaded properly? `loading annotation data from xml//Patient1.ndpi.xml`

After making your above changes, I still see this:
![image](https://user-images.githubusercontent.com/35524818/51764016-e2fa1180-20cb-11e9-9ac8-c6ebb615af58.png)


Did you mean change the .get() to something like .iter() even in lines 222 etc?

**Comment by btcrabb** [comment]
When it says, “Could not find, generating new file...” this means that it was unable to find the .xml file. Furthermore, since it is trying to load patient1.ndpi.xml, you didn’t remove the extra period in the filename like we discussed earlier. 

To be perfectly clear, there is going to have to be extensive changes to the xml file or the slideseg.py file in order to correctly load your annotations. If you are not incredibly familiar with python and/or programming, I would highly suggest pursuing something other than SlideSeg to process your whole slide images. If you still want to go this route, I will be available to answer questions when possible; however, I won’t be able to commit a serious amount of time into reprogramming the python module to make it compatible with .xml formats other than the one provided in the example.
